/**
 * Pure helpers for the rollout script.
 *
 * The script (`scripts/rollout-reviewer.ts`) does I/O — reads template
 * files, opens PRs against target repos. Everything that can be tested
 * without GitHub goes here.
 */

/**
 * Standard branch name for the rollout PR. We hard-code it so re-running the
 * script against the same repo is idempotent: if a branch with this name
 * already exists, we update it rather than creating a new one.
 */
export const ROLLOUT_BRANCH = "ogenticai-reviewer/install-v1";

/** Title used for the rollout PR — kept stable for find-or-update logic. */
export const ROLLOUT_PR_TITLE = "chore: install OgenticAI Reviewer (UAT-checklist gate)";

export interface RolloutFile {
  /** Repo-relative path the file should land at. */
  path: string;
  /** UTF-8 file contents. */
  content: string;
}

export interface RolloutPlan {
  /** Files we'd add or replace if the rollout runs against this repo. */
  files: RolloutFile[];
  /** What's already up-to-date on the target — these files DON'T need writing. */
  alreadyInstalled: string[];
  /** True when the plan would change something on the target repo. */
  changed: boolean;
}

/**
 * Compare templates against current target-repo state to decide what to write.
 * Pure: takes the desired files and the current contents (or null = absent),
 * returns the minimal set of writes.
 */
export function planRollout(args: {
  desired: RolloutFile[];
  currentContents: Record<string, string | null>;
}): RolloutPlan {
  const files: RolloutFile[] = [];
  const alreadyInstalled: string[] = [];

  for (const desired of args.desired) {
    const current = args.currentContents[desired.path];
    if (current === undefined) {
      throw new Error(
        `planRollout: no current content provided for ${desired.path} (pass null to indicate the file is absent)`,
      );
    }
    if (current !== null && normalize(current) === normalize(desired.content)) {
      alreadyInstalled.push(desired.path);
      continue;
    }
    files.push(desired);
  }

  return {
    files,
    alreadyInstalled,
    changed: files.length > 0,
  };
}

/**
 * The body posted on the rollout PR. Stays stable across re-runs so PRs
 * don't churn just because the script ran twice.
 */
export function rolloutPrBody(args: {
  repoSlug: string;
  appInstallUrl: string;
}): string {
  return [
    `Adds the **OgenticAI Reviewer** to \`${args.repoSlug}\`.`,
    ``,
    `## What lands`,
    ``,
    `1. \`.github/workflows/ogenticai-reviewer.yml\` — runs the reviewer on every PR (advisory mode; \`fail_on\` is empty).`,
    `2. \`.github/workflows/uat-override.yml\` — handles \`/uat-override <reason>\` slash commands from maintainers.`,
    ``,
    `## Before merging`,
    ``,
    `- [ ] **Install the OgenticAI Reviewer GitHub App** on this repo: ${args.appInstallUrl}`,
    `- [ ] Confirm the four org-level secrets exist (\`ANTHROPIC_API_KEY\`, \`OGENTICAI_REVIEWER_APP_ID\`, \`OGENTICAI_REVIEWER_APP_KEY\`, \`LINEAR_API_TOKEN\`)`,
    ``,
    `## After merging`,
    ``,
    `1. Open any PR — the reviewer will post a sticky comment within ~60s.`,
    `2. After 5–10 verdicts you trust, flip the merge gate by setting \`fail_on: NEEDS_WORK\` in the workflow input and running \`scripts/install-branch-protection.ts\` from \`OgenticAI/agent-reviewer\`.`,
    ``,
    `## Notes`,
    ``,
    `- v1 advisory by default. Auto-patch and merge-gating are opt-in.`,
    `- The reviewer never blocks merges on its own infra outages — Anthropic / Linear failures map to a \`neutral\` Check, not \`failure\`.`,
    `- Linked Linear ticket \`OGE-341\` tracks this rollout.`,
    ``,
    `---`,
    `_Auto-generated by \`scripts/rollout-reviewer.ts\` from \`OgenticAI/agent-reviewer\` · do not edit manually; re-run the script to update._`,
  ].join("\n");
}

/**
 * Strip CRLF + trailing whitespace before comparison so we don't churn PRs
 * based on line-ending or whitespace drift.
 */
function normalize(s: string): string {
  return s
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.replace(/[ \t]+$/, ""))
    .join("\n")
    .replace(/\n+$/, "\n");
}
