/**
 * The "this PR was NOT reviewed" comment (OGE-1655).
 *
 * A skipped review used to be completely silent. `runReview` throws
 * `ReviewSkippedError`, the CLI logs to stderr and exits 3, and the Action
 * publishes a `skipped` Check — which GitHub renders as a neutral, grey,
 * non-blocking result sitting next to the green ones. Nothing in the PR UI
 * says the reviewer declined. It looks exactly like a check that ran and had
 * no complaints.
 *
 * That makes omitting a markdown heading a silent bypass of the merge gate.
 * Not an attack — an accident, and one that already happened: on 2026-07-20 a
 * PR wrote `## Reviewer checklist` instead of `## UAT checklist` and went
 * unreviewed with nothing to show for it.
 *
 * Measured on the canary repo, **56–75% of runs skip**. So this is not an edge
 * case being tidied up; for most PRs the skip comment IS the reviewer's entire
 * output, and it needs to say plainly that no review happened.
 *
 * ── The re-trigger trap ─────────────────────────────────────────────────────
 *
 * The workflow fires on `opened, synchronize, ready_for_review`. Editing the PR
 * body to add the heading does NOT re-run it. Every message here says to push,
 * because telling someone to "add a checklist" without that detail sends them
 * to a fix that appears not to work.
 */

import { COMMENT_MARKER } from "../version.js";

/** Which precondition the review bailed on. */
export type SkipReason = "no-ticket" | "no-checklist" | "unknown";

/**
 * Classify a `ReviewSkippedError` message into a reason.
 *
 * Matched on the distinctive phrase rather than the whole string so a reworded
 * error doesn't silently degrade the comment to the generic branch.
 */
export function classifySkip(message: string): SkipReason {
  if (/no linear ticket/i.test(message)) return "no-ticket";
  if (/uat checklist/i.test(message)) return "no-checklist";
  return "unknown";
}

const BODIES: Record<SkipReason, { what: string; fix: string[] }> = {
  "no-checklist": {
    what:
      "This PR has no `## UAT checklist` block in its description, so there was " +
      "nothing to review against.",
    fix: [
      "Add a `## UAT checklist` heading to the PR description, with one `- [ ]` item per acceptance criterion.",
      "The heading must be exactly `## UAT checklist` — `## Reviewer checklist`, `## Checklist`, and `### UAT checklist` are all missed.",
    ],
  },
  "no-ticket": {
    what:
      "No Linear ticket id (`OGE-NNN`) was found in this PR's branch name, " +
      "description, or title, so there was no ticket to review against.",
    fix: [
      "Put the ticket id in the branch name (`david/oge-123-short-slug`), the PR title, or the description.",
      "Copy the branch name from the Linear ticket's \"Copy branch name\" button to get this right by default.",
    ],
  },
  unknown: {
    what: "The reviewer declined to review this PR.",
    fix: ["See the reason above and the reviewer's job log for detail."],
  },
};

/**
 * Render the skip notice.
 *
 * Carries `COMMENT_MARKER`, the same sticky marker a real verdict uses, so the
 * notice is REPLACED by the verdict once the PR is fixed rather than
 * accumulating alongside it.
 */
export function renderSkipComment(args: {
  reason: SkipReason;
  /** The raw error, quoted verbatim so the comment can't drift from the cause. */
  message: string;
  /**
   * Whether this skip fails the Check (OGE-1655 option 3). Changes the framing
   * from "be aware" to "this is blocking you", because those need different
   * urgency — and a blocking comment that reads as advisory wastes the author's
   * time working out why they can't merge.
   */
  blocking?: boolean;
}): string {
  const { what, fix } = BODIES[args.reason];
  const status = args.blocking
    ? [
        `## OgenticAI Reviewer — :no_entry: not reviewed, merge blocked`,
        ``,
        `**No UAT verdict was produced for this PR, and this repo requires one.** ${what}`,
        ``,
        `The \`OgenticAI Reviewer / UAT\` check is **failing** until a checklist exists.`,
      ]
    : [
        `## OgenticAI Reviewer — :warning: not reviewed`,
        ``,
        `**No UAT verdict was produced for this PR.** ${what}`,
        ``,
        `The \`OgenticAI Reviewer / UAT\` check will show as *skipped*, which looks`,
        `similar to a pass. It is not one — nothing here has been checked.`,
      ];
  return [
    COMMENT_MARKER,
    ``,
    ...status,
    ``,
    `### To get this reviewed`,
    ``,
    ...fix.map((f, i) => `${i + 1}. ${f}`),
    `${fix.length + 1}. **Push a commit.** Editing the PR description alone will _not_ re-run the reviewer —`,
    `   it only fires on \`opened\`, \`synchronize\`, and \`ready_for_review\`.`,
    ``,
    `<details><summary>Reviewer output</summary>`,
    ``,
    "```",
    args.message,
    "```",
    ``,
    `</details>`,
    ``,
    `---`,
    `_Auto-generated by **OgenticAI Reviewer** · do not edit_`,
  ].join("\n");
}
