import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  scanDependencyManifests,
  declaredPackages,
  describeUnscanned,
  npmLockfileDirs,
} from "../../src/engine/audit/dependencies.js";

let scratch: string;
beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), "deps-test-"));
});
afterEach(() => {
  rmSync(scratch, { recursive: true, force: true });
});

function write(rel: string, text: string): void {
  const full = join(scratch, rel);
  mkdirSync(join(full, ".."), { recursive: true });
  writeFileSync(full, text);
}

const CSPROJ = `<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="8.0.0" />
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
  </ItemGroup>
</Project>`;

/**
 * The real shape NuGet writes: `dependencies`, keyed by target framework, then
 * by package. The first fixture here was shaped to match a parser bug and
 * yielded the framework names as if they were packages.
 */
const NUGET_LOCK = JSON.stringify({
  version: 1,
  dependencies: {
    "net8.0": {
      Serilog: { type: "Direct", requested: "[3.0.0, )", resolved: "3.0.0", contentHash: "x" },
      "Newtonsoft.Json": { type: "Transitive", resolved: "13.0.1", contentHash: "y" },
    },
    "net8.0/win-x64": {
      Serilog: { type: "Direct", requested: "[3.0.0, )", resolved: "3.0.0", contentHash: "x" },
    },
  },
});

const PNPM_LOCK_V9 = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:

  .:
    dependencies:
      react:
        specifier: ^18
        version: 18.3.1
    devDependencies:
      vitest:
        specifier: ^2
        version: 2.1.0

packages:

  '@babel/core@7.24.0':
    resolution: {integrity: sha512-x}

  react@18.3.1:
    resolution: {integrity: sha512-y}

snapshots:

  '@babel/core@7.24.0':
    dependencies:
      react: 18.3.1
`;

const PNPM_LOCK_V6 = `lockfileVersion: '6.0'

dependencies:
  react:
    specifier: ^18
    version: 18.3.1

packages:

  /@babel/core@7.24.0:
    resolution: {integrity: sha512-x}

  /react@18.3.1:
    resolution: {integrity: sha512-y}
`;

const YARN_LOCK_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz"

react@^18.0.0:
  version "18.3.1"
`;

const YARN_LOCK_BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8

"@babel/core@npm:^7.0.0":
  version: 7.24.0

"react@npm:^18.0.0, react@npm:^18.2.0":
  version: 18.3.1
`;

describe("reading what a tree declares it depends on", () => {
  it("finds NuGet packages a .NET tree declares across many project files", () => {
    write("src/Api/Api.csproj", CSPROJ);
    write(
      "src/Domain/Domain.csproj",
      CSPROJ.replace("Ardalis.Specification", "Serilog"),
    );
    const [nuget] = scanDependencyManifests(scratch);
    expect(nuget?.ecosystem).toBe("nuget");
    expect(nuget?.manifests).toHaveLength(2);
    // Union, not sum: the same package declared twice is one dependency.
    expect(nuget?.packages).toBe(3);
    expect(nuget?.lockfile).toBe(false);
  });

  it("marks the graph as pinned only when a lockfile is present", () => {
    write("src/Api/Api.csproj", CSPROJ);
    expect(scanDependencyManifests(scratch)[0]?.lockfile).toBe(false);
    write("src/Api/packages.lock.json", NUGET_LOCK);
    expect(scanDependencyManifests(scratch)[0]?.lockfile).toBe(true);
  });

  // The lockfile nests packages under the target framework. Reading the top
  // level counted `net8.0` as a dependency and Serilog not at all.
  it("reads package names out of a NuGet lockfile, not target frameworks", () => {
    const names = declaredPackages("packages.lock.json", NUGET_LOCK).sort();
    expect(names).toEqual(["Newtonsoft.Json", "Serilog"]);
    expect(names).not.toContain("net8.0");
  });

  it("reads central package versions from Directory.Packages.props", () => {
    const props = `<Project><ItemGroup><PackageVersion Include="Serilog" Version="3.0.0" /></ItemGroup></Project>`;
    write("Directory.Packages.props", props);
    const [nuget] = scanDependencyManifests(scratch);
    expect(nuget?.ecosystem).toBe("nuget");
    expect(declaredPackages("Directory.Packages.props", props)).toEqual(["Serilog"]);
  });

  it("does not count the same tree twice through vendored directories", () => {
    write("package.json", JSON.stringify({ dependencies: { react: "^18" } }));
    write("node_modules/react/package.json", JSON.stringify({ dependencies: { loose: "1" } }));
    const [npm] = scanDependencyManifests(scratch);
    expect(npm?.manifests).toEqual(["package.json"]);
    expect(npm?.packages).toBe(1);
  });

  // `packages/` is where a monorepo keeps its own workspaces, and the first
  // version skipped it as though it were vendored. A repository of six
  // packages read as declaring nothing.
  it("walks a packages/ directory, because that is where a monorepo keeps its own code", () => {
    write("package.json", JSON.stringify({ name: "root", devDependencies: { turbo: "^2" } }));
    write("packages/api/package.json", JSON.stringify({ dependencies: { express: "^4" } }));
    write("packages/web/package.json", JSON.stringify({ dependencies: { react: "^18" } }));
    write("packages/web/node_modules/react/package.json", JSON.stringify({ dependencies: { loose: "1" } }));
    const [npm] = scanDependencyManifests(scratch);
    expect(npm?.manifests).toEqual(["package.json", "packages/api/package.json", "packages/web/package.json"]);
    expect(npm?.packages).toBe(3);
  });

  it("sorts ecosystems by size, so the biggest unscanned one is named first", () => {
    write("api/Api.csproj", CSPROJ);
    write("web/package.json", JSON.stringify({ dependencies: { react: "^18" } }));
    expect(scanDependencyManifests(scratch)[0]?.ecosystem).toBe("nuget");
  });

  it.each([
    ["packages.config", '<packages><package id="Newtonsoft.Json" version="13.0.1" /></packages>', "Newtonsoft.Json"],
    ["requirements.txt", "requests==2.31.0\n# a comment\nflask>=2\n", "requests"],
    ["pom.xml", "<dependency><artifactId>guava</artifactId></dependency>", "guava"],
  ])("reads %s", (name, text, expected) => {
    expect(declaredPackages(name, text)).toContain(expected);
  });

  // A pnpm tree IS lock-pinned. Not knowing the file read it as "declared only".
  it.each([
    ["pnpm-lock.yaml v9", "pnpm-lock.yaml", PNPM_LOCK_V9, ["@babel/core", "react", "vitest"]],
    ["pnpm-lock.yaml v6", "pnpm-lock.yaml", PNPM_LOCK_V6, ["@babel/core", "react"]],
    ["yarn.lock classic", "yarn.lock", YARN_LOCK_V1, ["@babel/core", "react"]],
    ["yarn.lock berry", "yarn.lock", YARN_LOCK_BERRY, ["@babel/core", "react"]],
  ])("reads names, and only names, out of %s", (_label, name, text, expected) => {
    const names = declaredPackages(name, text).sort();
    expect(names).toEqual(expected);
    // Versions and specifiers never leak in as names.
    expect(names.some((n) => /\d+\.\d+/.test(n) || n.includes("^"))).toBe(false);
  });

  it("marks a pnpm or yarn tree as lock-pinned", () => {
    write("package.json", JSON.stringify({ dependencies: { react: "^18" } }));
    expect(scanDependencyManifests(scratch)[0]?.lockfile).toBe(false);
    write("pnpm-lock.yaml", PNPM_LOCK_V9);
    const [npm] = scanDependencyManifests(scratch);
    expect(npm?.lockfile).toBe(true);
    expect(npm?.packages).toBe(3);
  });

  it("reads a v3 package-lock down to the innermost nested package", () => {
    const lock = JSON.stringify({
      lockfileVersion: 3,
      packages: {
        "": { dependencies: { a: "1" } },
        "node_modules/a": { version: "1.0.0" },
        "node_modules/a/node_modules/b": { version: "2.0.0" },
      },
    });
    expect(declaredPackages("package-lock.json", lock).sort()).toEqual(["a", "b"]);
  });

  // A manifest we cannot parse is still a manifest. Crashing the walk would
  // lose every other ecosystem in the tree.
  it("counts an unparseable manifest as present with nothing declared", () => {
    write("web/package.json", "{ this is not json");
    const [npm] = scanDependencyManifests(scratch);
    expect(npm?.manifests).toEqual(["web/package.json"]);
    expect(npm?.packages).toBe(0);
  });
});

describe("where npm audit has a lockfile to read", () => {
  it("lists every directory with a lockfile npm audit can read, root first", () => {
    write("package-lock.json", "{}");
    write("client/package-lock.json", "{}");
    write("tools/npm-shrinkwrap.json", "{}");
    expect(npmLockfileDirs(scratch)).toEqual(["", "client", "tools"]);
  });

  it("does not offer a pnpm or yarn lockfile to npm audit, which cannot read them", () => {
    write("pnpm-lock.yaml", PNPM_LOCK_V9);
    write("web/yarn.lock", YARN_LOCK_V1);
    expect(npmLockfileDirs(scratch)).toEqual([]);
  });
});

describe("the sentence a skipped scan prints", () => {
  // "No npm lockfile at the repository root" is true over a .NET tree and reads
  // as "there is nothing here". A reader has to be told what went unexamined.
  it("names the count, the ecosystem, and that nothing was checked", () => {
    write("src/Api/Api.csproj", CSPROJ);
    const message = describeUnscanned(scanDependencyManifests(scratch), []);
    expect(message).toMatch(/2 nuget package\(s\)/);
    expect(message).toMatch(/NOT checked/);
  });

  // Without a lockfile the count is a floor. Presenting it as a total would be
  // the same error the report exists to avoid.
  it("says a count is declared-only when no lockfile pins the graph", () => {
    write("src/Api/Api.csproj", CSPROJ);
    expect(describeUnscanned(scanDependencyManifests(scratch), [])).toMatch(/not lock-pinned/);
  });

  // Two different causes, two different sentences. Blaming a missing advisory
  // source for an npm tree sends the reader to install a tool they have.
  it("blames a missing lockfile for npm, and a missing advisory source for everything else", () => {
    write("web/package.json", JSON.stringify({ dependencies: { react: "^18" } }));
    write("src/Api/Api.csproj", CSPROJ);
    const message = describeUnscanned(scanDependencyManifests(scratch), [])!;
    expect(message).toMatch(/npm audit needs a package-lock\.json or npm-shrinkwrap\.json/);
    expect(message).toMatch(/no advisory source is available for nuget/);
    expect(message).not.toMatch(/advisory source is available for [^.]*npm/);
  });

  it("says the lockfile present is one npm audit cannot read, when that is the case", () => {
    write("package.json", JSON.stringify({ dependencies: { react: "^18" } }));
    write("pnpm-lock.yaml", PNPM_LOCK_V9);
    const message = describeUnscanned(scanDependencyManifests(scratch), [])!;
    expect(message).toMatch(/pnpm or yarn lockfile/);
    expect(message).not.toMatch(/not lock-pinned/);
  });

  it("says nothing when every ecosystem found was scanned", () => {
    write("web/package.json", JSON.stringify({ dependencies: { react: "^18" } }));
    expect(describeUnscanned(scanDependencyManifests(scratch), ["npm"])).toBeNull();
  });

  it("says nothing for a tree that declares no dependencies at all", () => {
    write("src/main.go", "package main");
    expect(describeUnscanned(scanDependencyManifests(scratch), [])).toBeNull();
  });
});
