/**
 * Linear comment renderer — mirrors the PR sticky verdict to the linked ticket.
 *
 * The Linear comment is a *summary*, not a duplicate of the full PR comment.
 * Linear's threading + per-issue notification model means a giant repeated
 * comment is louder than useful. We give the verdict overall, the per-item
 * status counts, and a link to the PR's full sticky comment table.
 *
 * Idempotency: same verdict → byte-identical comment body, just like the PR
 * sticky. The marker on the first line lets the writeback layer find the
 * existing comment to update instead of creating a duplicate.
 */

import type { ReviewVerdict, VerdictStatus } from "../schema/verdict.js";
import type { OverallStatus } from "../schema/verdict.js";
import { REVIEWER_VERSION } from "../version.js";

/**
 * Marker used to find the bot's existing comment on a Linear ticket. Linear
 * markdown supports HTML comments (rendered as hidden in the UI), so this
 * doesn't pollute the visible body.
 */
export const LINEAR_COMMENT_MARKER = `<!-- ogenticai-reviewer-${REVIEWER_VERSION} -->`;

const OVERALL_HEADLINE: Record<OverallStatus, string> = {
  PASS: "✅ All UAT items pass.",
  PASS_WITH_PARTIALS: "🟡 UAT passes with partials — review the partial rationales before merging.",
  NEEDS_WORK: "❌ UAT fails — at least one item is not delivered.",
  HUMAN_REVIEW: "🤔 UAT needs human review — at least one item can't be verified from the diff.",
};

const STATUS_BADGE: Record<VerdictStatus, string> = {
  PASS: "✅",
  FAIL: "❌",
  PARTIAL: "🟡",
  UNVERIFIABLE: "🤔",
};

export function renderLinearComment(args: {
  verdict: ReviewVerdict;
  prUrl: string;
  overall: OverallStatus;
}): string {
  const counts = countByStatus(args.verdict);
  const lines: string[] = [];

  lines.push(LINEAR_COMMENT_MARKER);
  lines.push("");
  lines.push(`**OgenticAI Reviewer · UAT verdict** for [${args.verdict.prRef}](${args.prUrl})`);
  lines.push("");
  lines.push(OVERALL_HEADLINE[args.overall]);
  lines.push("");

  if (args.verdict.summary.trim()) {
    lines.push(`> ${args.verdict.summary.trim()}`);
    lines.push("");
  }

  const tally = (Object.entries(counts) as [VerdictStatus, number][])
    .filter(([, n]) => n > 0)
    .map(([status, n]) => `${STATUS_BADGE[status]} ${n} ${status}`)
    .join(" · ");
  lines.push(`**Items:** ${tally || "none"}`);
  lines.push("");
  lines.push(`See the [full per-item table on the PR](${args.prUrl}) for rationales and evidence.`);
  lines.push("");
  lines.push(`---`);
  lines.push(`_Auto-generated by **OgenticAI Reviewer ${REVIEWER_VERSION}** · do not edit_`);

  return lines.join("\n");
}

function countByStatus(verdict: ReviewVerdict): Record<VerdictStatus, number> {
  const counts: Record<VerdictStatus, number> = {
    PASS: 0,
    FAIL: 0,
    PARTIAL: 0,
    UNVERIFIABLE: 0,
  };
  for (const it of verdict.items) counts[it.status] += 1;
  return counts;
}
