/**
 * Linear comment renderer — mirrors the PR sticky verdict to the linked ticket.
 *
 * The Linear comment is a *summary*, not a duplicate of the full PR comment.
 * Linear's threading + per-issue notification model means a giant repeated
 * comment is louder than useful. We give the verdict overall, the per-item
 * status counts, and a link to the PR's full sticky comment table.
 *
 * Idempotency: same verdict → byte-identical comment body, just like the PR
 * sticky. The marker on the first line lets the writeback layer find the
 * existing comment to update instead of creating a duplicate.
 */

import type { ReviewVerdict, VerdictStatus } from "../schema/verdict.js";
import type { OverallStatus } from "../schema/verdict.js";
import { REVIEWER_VERSION } from "../version.js";
import {
  computeVerdictMetrics,
  renderMetricsBlock,
  type VerdictMetrics,
} from "../metrics/verdict-metrics.js";

/**
 * Marker used to find the bot's existing comment on a Linear ticket. Linear
 * markdown supports HTML comments (rendered as hidden in the UI), so this
 * doesn't pollute the visible body.
 */
export const LINEAR_COMMENT_MARKER = `<!-- ogenticai-reviewer-${REVIEWER_VERSION} -->`;

const OVERALL_HEADLINE: Record<OverallStatus, string> = {
  PASS: "✅ All UAT items pass.",
  PASS_WITH_PARTIALS: "🟡 UAT passes with partials — review the partial rationales before merging.",
  NEEDS_WORK: "❌ UAT fails — at least one item is not delivered.",
  HUMAN_REVIEW: "🤔 UAT needs human review — at least one item can't be verified from the diff.",
};

const STATUS_BADGE: Record<VerdictStatus, string> = {
  PASS: "✅",
  CODE_VERIFIED: "🟢",
  FAIL: "❌",
  PARTIAL: "🟡",
  UNVERIFIABLE: "🤔",
};

/** Per-item rationales are mirrored, but Linear comments shouldn't be walls. */
const RATIONALE_MAX_CHARS = 220;

export function renderLinearComment(args: {
  verdict: ReviewVerdict;
  prUrl: string;
  overall: OverallStatus;
  /** Run telemetry for the metrics block (OGE-1562). Defaults to a cache-less, tool-less run. */
  metrics?: Partial<Pick<VerdictMetrics, "toolCalls" | "researchQueries" | "cached" | "degraded">> & {
    puntsBefore?: number;
    puntsAfter?: number;
  };
}): string {
  const counts = countByStatus(args.verdict);
  const lines: string[] = [];

  lines.push(LINEAR_COMMENT_MARKER);
  lines.push("");
  lines.push(`**OgenticAI Reviewer · UAT verdict** for [${args.verdict.prRef}](${args.prUrl})`);
  lines.push("");
  lines.push(OVERALL_HEADLINE[args.overall]);
  lines.push("");

  if (args.verdict.summary.trim()) {
    lines.push(`> ${args.verdict.summary.trim()}`);
    lines.push("");
  }

  const tally = (Object.entries(counts) as [VerdictStatus, number][])
    .filter(([, n]) => n > 0)
    .map(([status, n]) => `${STATUS_BADGE[status]} ${n} ${status}`)
    .join(" · ");
  lines.push(`**Items:** ${tally || "none"}`);
  lines.push("");

  // Mirror the per-item verdicts (OGE-1562).
  //
  // This block used to be a single line pointing at the PR. That made Linear
  // useless as a data source: the per-item rationales — the "why" behind every
  // punt, and the only place the reviewer explains itself — lived solely on
  // GitHub. Measuring the 88% baseline meant reading PRs by hand. Anyone
  // auditing the reviewer, in either tool, should see the same reasoning.
  if (args.verdict.items.length > 0) {
    lines.push("| # | Item | Verdict | Rationale |");
    lines.push("|---|------|---------|-----------|");
    for (const item of args.verdict.items) {
      const marker = item.human === true ? " `[human]`" : "";
      lines.push(
        `| ${item.id} | ${cell(item.itemText)}${marker} | ${STATUS_BADGE[item.status]} ${item.status} | ${cell(truncate(item.rationale))} |`,
      );
    }
    lines.push("");
  }

  lines.push(`See the [full evidence links on the PR](${args.prUrl}).`);
  lines.push("");
  lines.push(`---`);
  lines.push(`_Auto-generated by **OgenticAI Reviewer ${REVIEWER_VERSION}** · do not edit_`);
  lines.push(
    renderMetricsBlock(
      computeVerdictMetrics({
        verdict: args.verdict,
        toolCalls: args.metrics?.toolCalls ?? 0,
        researchQueries: args.metrics?.researchQueries ?? 0,
        cached: args.metrics?.cached ?? false,
        ...(args.metrics?.degraded ? { degraded: args.metrics.degraded } : {}),
        ...(args.metrics?.puntsBefore !== undefined
          ? { puntsBefore: args.metrics.puntsBefore, puntsAfter: args.metrics.puntsAfter }
          : {}),
      }),
    ),
  );

  return lines.join("\n");
}

function countByStatus(verdict: ReviewVerdict): Record<VerdictStatus, number> {
  const counts: Record<VerdictStatus, number> = {
    PASS: 0,
    CODE_VERIFIED: 0,
    FAIL: 0,
    PARTIAL: 0,
    UNVERIFIABLE: 0,
  };
  for (const it of verdict.items) counts[it.status] += 1;
  return counts;
}

/** Make text safe for a Markdown table cell. */
function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function truncate(s: string): string {
  return s.length > RATIONALE_MAX_CHARS ? `${s.slice(0, RATIONALE_MAX_CHARS)}…` : s;
}
