/**
 * Token-budgeted diff packing (OGE-1581) and hunk expansion (OGE-1591).
 *
 * The property that matters most is not "fits the budget" — it is **nothing
 * disappears silently**. A dropped file the model never hears about produces a
 * confident PASS on a change it never saw; a dropped file it is told about
 * produces either a targeted `read_file` or an honest punt. Several tests below
 * exist only to pin that distinction.
 */

import { describe, expect, it } from "vitest";

import {
  estimateTokens,
  expandHunkStart,
  expandPatchContext,
  matchesGlob,
  packDiff,
  splitDiff,
} from "../../src/prompt/diff-pack.js";

function patchFor(path: string, addedLines = 3): string {
  const body = Array.from({ length: addedLines }, (_, i) => `+line ${i}`).join("\n");
  return [
    `diff --git a/${path} b/${path}`,
    `--- a/${path}`,
    `+++ b/${path}`,
    `@@ -1,2 +1,${addedLines} @@`,
    ` context`,
    body,
  ].join("\n");
}

describe("splitDiff", () => {
  it("splits a multi-file diff and counts additions", () => {
    const files = splitDiff([patchFor("src/a.ts", 2), patchFor("src/b.ts", 5)].join("\n"));
    expect(files.map((f) => f.path)).toEqual(["src/a.ts", "src/b.ts"]);
    expect(files[1]!.additions).toBe(5);
  });

  it("uses the b/ path so a rename points at where the code now lives", () => {
    const renamed = ["diff --git a/old.ts b/new.ts", "--- a/old.ts", "+++ b/new.ts", "+x"].join("\n");
    expect(splitDiff(renamed)[0]!.path).toBe("new.ts");
  });

  it("returns nothing for an empty diff", () => {
    expect(splitDiff("")).toEqual([]);
    expect(splitDiff("   \n")).toEqual([]);
  });
});

describe("matchesGlob", () => {
  it("matches ** across separators and * within a segment", () => {
    expect(matchesGlob("src/gen/a.ts", "src/**")).toBe(true);
    expect(matchesGlob("src/a.ts", "src/*.ts")).toBe(true);
    expect(matchesGlob("src/deep/a.ts", "src/*.ts")).toBe(false);
  });

  it("does not treat a dot as a wildcard", () => {
    expect(matchesGlob("srcXa.ts", "src.a.ts")).toBe(false);
  });
});

describe("packDiff — dropping the right things", () => {
  it("strips lockfiles and build output without spending budget", () => {
    const result = packDiff([patchFor("src/a.ts"), patchFor("package-lock.json", 900)].join("\n"));
    expect(result.includedFiles).toEqual(["src/a.ts"]);
    expect(result.skippedFiles).toContainEqual({ path: "package-lock.json", reason: "generated" });
  });

  it("honours exclude globs", () => {
    const result = packDiff([patchFor("src/a.ts"), patchFor("generated/x.ts")].join("\n"), {
      excludeGlobs: ["generated/**"],
    });
    expect(result.includedFiles).toEqual(["src/a.ts"]);
    expect(result.skippedFiles[0]!.reason).toBe("excluded");
  });

  it("detects an @generated marker in added lines", () => {
    const gen = [
      "diff --git a/src/api.ts b/src/api.ts",
      "+++ b/src/api.ts",
      "@@ -1 +1,2 @@",
      "+// @generated by openapi",
      "+export const x = 1;",
    ].join("\n");
    expect(packDiff(gen).skippedFiles[0]).toEqual({ path: "src/api.ts", reason: "generated" });
  });

  it("does NOT classify a file as generated when the marker is being removed", () => {
    const unmarking = [
      "diff --git a/src/api.ts b/src/api.ts",
      "+++ b/src/api.ts",
      "@@ -1,2 +1 @@",
      "-// @generated by openapi",
      "+export const x = 1;",
    ].join("\n");
    expect(packDiff(unmarking).includedFiles).toEqual(["src/api.ts"]);
  });
});

describe("packDiff — budget", () => {
  it("respects the token budget on an oversized diff", () => {
    const big = Array.from({ length: 40 }, (_, i) => patchFor(`src/f${i}.ts`, 200)).join("\n");
    const result = packDiff(big, { tokenBudget: 2000 });
    expect(estimateTokens(result.text)).toBeLessThanOrEqual(2400);
    expect(result.truncated).toBe(true);
  });

  it("names every dropped file so the model can fetch or punt", () => {
    // The whole safety argument: silence would produce a confident PASS on an
    // unseen change.
    const big = Array.from({ length: 12 }, (_, i) => patchFor(`src/f${i}.ts`, 200)).join("\n");
    const result = packDiff(big, { tokenBudget: 500 });
    const dropped = result.skippedFiles.filter((s) => s.reason === "token-budget");
    expect(dropped.length).toBeGreaterThan(0);
    expect(result.text).toContain("Not inlined (token budget)");
    for (const d of dropped) expect(result.text).toContain(d.path);
  });

  it("always includes at least one file, even when it alone exceeds the budget", () => {
    const result = packDiff(patchFor("src/huge.ts", 5000), { tokenBudget: 10 });
    expect(result.includedFiles).toEqual(["src/huge.ts"]);
  });

  it("adds no skip header when everything fits", () => {
    const result = packDiff(patchFor("src/a.ts"));
    expect(result.truncated).toBe(false);
    expect(result.text).not.toContain("Not inlined");
  });
});

describe("packDiff — relevance ordering", () => {
  it("packs a checklist-named file before a larger unrelated one", () => {
    const diff = [patchFor("src/unrelated.ts", 400), patchFor("src/redaction.ts", 5)].join("\n");
    const result = packDiff(diff, {
      tokenBudget: 200,
      checklistTexts: ["`redaction` round-trips across all profiles"],
    });
    expect(result.includedFiles[0]).toBe("src/redaction.ts");
  });

  it("prefers additions-heavy patches when relevance ties", () => {
    // New behaviour is what a UAT item asserts; deletions rarely settle one.
    const diff = [patchFor("src/a.ts", 2), patchFor("src/b.ts", 50)].join("\n");
    expect(packDiff(diff).includedFiles[0]).toBe("src/b.ts");
  });
});

describe("expandHunkStart — dynamic context (OGE-1591)", () => {
  const file = [
    "import x from 'y';", // 1
    "", // 2
    "export function redact(input: string) {", // 3
    "  const a = 1;", // 4
    "  const b = 2;", // 5
    "  return a + b;", // 6
    "}", // 7
  ];

  it("expands to the enclosing function definition", () => {
    expect(expandHunkStart(file, 6)).toBe(3);
  });

  it("falls back to a fixed lead-in when no boundary is within reach", () => {
    const flat = Array.from({ length: 40 }, (_, i) => `const v${i} = ${i};`);
    expect(expandHunkStart(flat, 30)).toBe(27); // 30 - 3
  });

  it("never returns a line before the start of the file", () => {
    expect(expandHunkStart(file, 1)).toBeGreaterThanOrEqual(1);
  });
});

describe("expandPatchContext", () => {
  const content = [
    "import x from 'y';",
    "",
    "export function redact(input: string) {",
    "  const a = 1;",
    "  const b = 2;",
    "  return a + b;",
    "}",
  ].join("\n");

  it("prepends the enclosing function to a hunk", () => {
    const patch = [
      "diff --git a/src/redaction.ts b/src/redaction.ts",
      "+++ b/src/redaction.ts",
      "@@ -5,1 +5,2 @@",
      "+  const c = 3;",
    ].join("\n");
    const out = expandPatchContext(
      { path: "src/redaction.ts", patch, additions: 1, deletions: 0 },
      () => content,
    );
    expect(out).toContain("export function redact(input: string) {");
  });

  it("leaves the patch alone when the file cannot be read", () => {
    const patch = patchFor("src/a.ts");
    expect(
      expandPatchContext({ path: "src/a.ts", patch, additions: 1, deletions: 0 }, () => null),
    ).toBe(patch);
  });

  it("does not expand markdown", () => {
    const patch = [
      "diff --git a/README.md b/README.md",
      "+++ b/README.md",
      "@@ -5,1 +5,2 @@",
      "+text",
    ].join("\n");
    expect(
      expandPatchContext({ path: "README.md", patch, additions: 1, deletions: 0 }, () => content),
    ).toBe(patch);
  });

  it("counts expanded content against the budget", () => {
    // Expansion runs before measuring, or budgets silently under-count.
    const patch = [
      "diff --git a/src/redaction.ts b/src/redaction.ts",
      "+++ b/src/redaction.ts",
      "@@ -6,1 +6,2 @@",
      "+  const c = 3;",
    ].join("\n");
    const packed = packDiff(patch, { readFile: () => content, tokenBudget: 5000 });
    expect(packed.text).toContain("export function redact");
  });

  it("skips expansion entirely when no reader is supplied", () => {
    const packed = packDiff(patchFor("src/a.ts"));
    expect(packed.includedFiles).toEqual(["src/a.ts"]);
  });
});
